import { ok, collection, fail } from './response.js';
import { sessionContext, requireAuth, requireManager, requireCourse } from './auth/middleware.js';
import { requireText, optionalText, numberIn, safeUrl, oneOf, bool, ValidationError } from './validation.js';
import { first, all } from './db.js';
import { assertSubjectInCourse } from './course-context.js';
import { id, now } from './security.js';

const match=(path,pattern)=>{const keys=[];const rx=new RegExp('^'+pattern.replace(/:[^/]+/g,t=>{keys.push(t.slice(1));return'([^/]+)'})+'$');const m=path.match(rx);return m?Object.fromEntries(keys.map((k,i)=>[k,decodeURIComponent(m[i+1])])):null};
const jsonBody=async req=>{if(!(req.headers.get('content-type')||'').includes('application/json'))throw Object.assign(new Error('JSON body required'),{status:400,code:'JSON_REQUIRED'});return req.json()};
const audit=async(env,ctx,action,kind,entityId,target=null,meta={})=>env.DB.prepare(`INSERT INTO audit_events(id,actor_user_id,target_user_id,action,entity_kind,entity_id,course_id,metadata,request_id,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)`).bind(id('aud'),ctx.user.id,target,action,kind,entityId,ctx.activeCourse?.id||null,JSON.stringify(meta),ctx.requestId,now()).run();

export async function handleExtendedApi(request,env){
 const url=new URL(request.url),path=url.pathname,requestId=crypto.randomUUID(),ctx={...(await sessionContext(request,env)),requestId};
 try{
  let p;
  p=match(path,'/api/courses/:courseId/members');if(p&&request.method==='GET'){requireManager(ctx);return collection(await all(env.DB,`SELECT a.id,a.full_name,a.username,a.status,ce.position,ce.active,ce.source FROM course_enrollments ce JOIN accounts a ON a.id=ce.user_id WHERE ce.course_id=? ORDER BY a.full_name`,p.courseId))}
  p=match(path,'/api/courses/:courseId/subjects/:subjectId');if(p&&request.method==='POST'){requireManager(ctx);await env.DB.prepare(`INSERT OR IGNORE INTO course_subjects(course_id,subject_id,sort_order,created_at) VALUES(?,?,?,?)`).bind(p.courseId,p.subjectId,0,now()).run();await audit(env,ctx,'course.subject.assign','course_subject',p.subjectId,null,{courseId:p.courseId});return ok({courseId:p.courseId,subjectId:p.subjectId},201)}
  if(p&&request.method==='DELETE'){requireManager(ctx);await env.DB.prepare(`DELETE FROM course_subjects WHERE course_id=? AND subject_id=?`).bind(p.courseId,p.subjectId).run();await audit(env,ctx,'course.subject.remove','course_subject',p.subjectId,null,{courseId:p.courseId});return new Response(null,{status:204})}

  p=match(path,'/api/subjects/:subjectId/degrees');if(p&&request.method==='GET'){const user=requireAuth(ctx),course=requireCourse(ctx);await assertSubjectInCourse(env.DB,p.subjectId,course.id);let target=user.id;if(user.role==='MANAGER'&&url.searchParams.get('userId'))target=url.searchParams.get('userId');return collection(await all(env.DB,`SELECT * FROM degree_records WHERE user_id=? AND course_id=? AND subject_id=? ORDER BY recorded_at DESC`,target,course.id,p.subjectId))}
  if(path==='/api/degrees'&&request.method==='POST'){requireManager(ctx);const course=requireCourse(ctx),b=await jsonBody(request);await assertSubjectInCourse(env.DB,b.subject_id,course.id);if(!await first(env.DB,`SELECT 1 ok FROM course_enrollments WHERE user_id=? AND course_id=?`,b.user_id,course.id))return fail('NOT_ENROLLED','Student is not enrolled in this course',409,requestId);const score=numberIn(b.score,0,1e9,'score'),max=numberIn(b.max_score,0.000001,1e9,'max_score');if(score>max)throw new ValidationError({score:'Score cannot exceed maximum score'});const did=id('deg');await env.DB.prepare(`INSERT INTO degree_records(id,user_id,course_id,subject_id,title,assessment_kind,score,max_score,recorded_by,recorded_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)`).bind(did,b.user_id,course.id,b.subject_id,requireText(b,'title',200),requireText(b,'assessment_kind',80),score,max,ctx.user.id,now(),now()).run();await audit(env,ctx,'degree.create','degree',did,b.user_id);return ok(await first(env.DB,`SELECT * FROM degree_records WHERE id=?`,did),201)}
  p=match(path,'/api/degrees/:degreeId');if(p&&request.method==='PATCH'){requireManager(ctx);const b=await jsonBody(request),r=await first(env.DB,`SELECT * FROM degree_records WHERE id=?`,p.degreeId);if(!r)return fail('NOT_FOUND','Assessment not found',404,requestId);const score='score'in b?numberIn(b.score,0,1e9,'score'):r.score,max='max_score'in b?numberIn(b.max_score,.000001,1e9,'max_score'):r.max_score;if(score>max)throw new ValidationError({score:'Score cannot exceed maximum score'});await env.DB.prepare(`UPDATE degree_records SET title=?,assessment_kind=?,score=?,max_score=?,updated_at=? WHERE id=?`).bind(b.title??r.title,b.assessment_kind??r.assessment_kind,score,max,now(),r.id).run();await audit(env,ctx,'degree.update','degree',r.id,r.user_id);return ok(await first(env.DB,`SELECT * FROM degree_records WHERE id=?`,r.id))}
  if(p&&request.method==='DELETE'){requireManager(ctx);const r=await first(env.DB,`SELECT * FROM degree_records WHERE id=?`,p.degreeId);if(!r)return fail('NOT_FOUND','Assessment not found',404,requestId);await env.DB.prepare(`DELETE FROM degree_records WHERE id=?`).bind(r.id).run();await audit(env,ctx,'degree.delete','degree',r.id,r.user_id);return new Response(null,{status:204})}

  p=match(path,'/api/lectures/:lectureId/resources');if(p&&request.method==='POST'){requireManager(ctx);const b=await jsonBody(request),rid=id('res');await env.DB.prepare(`INSERT INTO lecture_resources(id,lecture_id,title,url,resource_kind,sort_order,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)`).bind(rid,p.lectureId,requireText(b,'title',200),safeUrl(b.url),b.resource_kind||'link',Number(b.sort_order||0),ctx.user.id,now(),now()).run();return ok(await first(env.DB,`SELECT * FROM lecture_resources WHERE id=?`,rid),201)}
  p=match(path,'/api/lecture-resources/:resourceId');if(p&&request.method==='PATCH'){requireManager(ctx);const b=await jsonBody(request),r=await first(env.DB,`SELECT * FROM lecture_resources WHERE id=?`,p.resourceId);if(!r)return fail('NOT_FOUND','Resource not found',404,requestId);await env.DB.prepare(`UPDATE lecture_resources SET title=?,url=?,resource_kind=?,sort_order=?,updated_at=? WHERE id=?`).bind(b.title??r.title,b.url?safeUrl(b.url):r.url,b.resource_kind??r.resource_kind,b.sort_order??r.sort_order,now(),r.id).run();return ok(await first(env.DB,`SELECT * FROM lecture_resources WHERE id=?`,r.id))}
  if(p&&request.method==='DELETE'){requireManager(ctx);await env.DB.prepare(`DELETE FROM lecture_resources WHERE id=?`).bind(p.resourceId).run();return new Response(null,{status:204})}

  p=match(path,'/api/posts/:postId/comments/:commentId');if(p&&request.method==='PATCH'){const user=requireAuth(ctx),c=await first(env.DB,`SELECT * FROM community_comments WHERE id=? AND post_id=?`,p.commentId,p.postId);if(!c||c.user_id!==user.id)return fail('NOT_FOUND','Comment not found',404,requestId);const b=await jsonBody(request);await env.DB.prepare(`UPDATE community_comments SET body=?,updated_at=? WHERE id=?`).bind(requireText(b,'body',5000),now(),c.id).run();return ok(await first(env.DB,`SELECT * FROM community_comments WHERE id=?`,c.id))}
  if(p&&request.method==='DELETE'){const user=requireAuth(ctx),c=await first(env.DB,`SELECT * FROM community_comments WHERE id=? AND post_id=?`,p.commentId,p.postId);if(!c||(c.user_id!==user.id&&user.role!=='MANAGER'))return fail('NOT_FOUND','Comment not found',404,requestId);await env.DB.prepare(`DELETE FROM community_comments WHERE id=?`).bind(c.id).run();return new Response(null,{status:204})}

  p=match(path,'/api/rooms/:roomId/requests/:userId');if(p&&request.method==='PATCH'){const user=requireAuth(ctx),room=await first(env.DB,`SELECT * FROM study_rooms WHERE id=?`,p.roomId);if(!room||(room.owner_id!==user.id&&user.role!=='MANAGER'))return fail('FORBIDDEN','Host access required',403,requestId);const b=await jsonBody(request),status=oneOf(b.status,['Approved','Declined'],'status');const req=await first(env.DB,`SELECT * FROM room_join_requests WHERE room_id=? AND user_id=? AND status='Pending'`,room.id,p.userId);if(!req)return fail('NOT_FOUND','Pending request not found',404,requestId);if(status==='Approved'){const count=(await first(env.DB,`SELECT COUNT(*) count FROM room_members WHERE room_id=?`,room.id)).count;if(room.status!=='Open'||count>=room.capacity)return fail('ROOM_FULL','Room cannot accept another member',409,requestId);await env.DB.batch([env.DB.prepare(`UPDATE room_join_requests SET status='Approved',updated_at=? WHERE room_id=? AND user_id=?`).bind(now(),room.id,p.userId),env.DB.prepare(`INSERT OR IGNORE INTO room_members(room_id,user_id,role,joined_at) VALUES(?,?,'Member',?)`).bind(room.id,p.userId,now())])}else await env.DB.prepare(`UPDATE room_join_requests SET status='Declined',updated_at=? WHERE room_id=? AND user_id=?`).bind(now(),room.id,p.userId).run();return ok({status})}
  p=match(path,'/api/rooms/:roomId/resources');if(p&&request.method==='POST'){const user=requireAuth(ctx);if(!await first(env.DB,`SELECT 1 ok FROM room_members WHERE room_id=? AND user_id=?`,p.roomId,user.id)&&user.role!=='MANAGER')return fail('FORBIDDEN','Membership required',403,requestId);const b=await jsonBody(request),rid=id('rr');await env.DB.prepare(`INSERT INTO room_resources(id,room_id,user_id,title,url,note,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)`).bind(rid,p.roomId,user.id,requireText(b,'title',200),safeUrl(b.url),optionalText(b,'note',1000),now(),now()).run();return ok(await first(env.DB,`SELECT * FROM room_resources WHERE id=?`,rid),201)}
  p=match(path,'/api/rooms/:roomId/resources/:resourceId');if(p&&request.method==='DELETE'){const user=requireAuth(ctx),r=await first(env.DB,`SELECT rr.*,sr.owner_id FROM room_resources rr JOIN study_rooms sr ON sr.id=rr.room_id WHERE rr.id=? AND rr.room_id=?`,p.resourceId,p.roomId);if(!r||(r.user_id!==user.id&&r.owner_id!==user.id&&user.role!=='MANAGER'))return fail('FORBIDDEN','Not allowed',403,requestId);await env.DB.prepare(`DELETE FROM room_resources WHERE id=?`).bind(r.id).run();return new Response(null,{status:204})}
  p=match(path,'/api/rooms/:roomId/tasks');if(p&&request.method==='POST'){const user=requireAuth(ctx);if(!await first(env.DB,`SELECT 1 ok FROM room_members WHERE room_id=? AND user_id=?`,p.roomId,user.id)&&user.role!=='MANAGER')return fail('FORBIDDEN','Membership required',403,requestId);const b=await jsonBody(request),tid=id('task');await env.DB.prepare(`INSERT INTO room_tasks(id,room_id,creator_id,title,due_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?)`).bind(tid,p.roomId,user.id,requireText(b,'title',300),b.due_at||null,now(),now()).run();return ok(await first(env.DB,`SELECT * FROM room_tasks WHERE id=?`,tid),201)}
  p=match(path,'/api/rooms/:roomId/tasks/:taskId/complete');if(p&&request.method==='POST'){const user=requireAuth(ctx);if(!await first(env.DB,`SELECT 1 ok FROM room_members WHERE room_id=? AND user_id=?`,p.roomId,user.id)&&user.role!=='MANAGER')return fail('FORBIDDEN','Membership required',403,requestId);const exists=await first(env.DB,`SELECT 1 ok FROM room_task_completions WHERE task_id=? AND user_id=?`,p.taskId,user.id),b=await request.json().catch(()=>({})),wanted=typeof b.completed==='boolean'?b.completed:!exists;if(wanted&&!exists)await env.DB.prepare(`INSERT INTO room_task_completions(task_id,user_id,completed_at) VALUES(?,?,?)`).bind(p.taskId,user.id,now()).run();if(!wanted&&exists)await env.DB.prepare(`DELETE FROM room_task_completions WHERE task_id=? AND user_id=?`).bind(p.taskId,user.id).run();return ok({completed:wanted})}
  p=match(path,'/api/rooms/:roomId/transfer-host');if(p&&request.method==='POST'){const user=requireAuth(ctx),room=await first(env.DB,`SELECT * FROM study_rooms WHERE id=?`,p.roomId);if(!room||(room.owner_id!==user.id&&user.role!=='MANAGER'))return fail('FORBIDDEN','Host access required',403,requestId);const b=await jsonBody(request);if(!await first(env.DB,`SELECT 1 ok FROM room_members WHERE room_id=? AND user_id=?`,room.id,b.user_id))return fail('NOT_MEMBER','New host must already be a member',409,requestId);await env.DB.batch([env.DB.prepare(`UPDATE room_members SET role='Member' WHERE room_id=? AND role='Host'`).bind(room.id),env.DB.prepare(`UPDATE room_members SET role='Host' WHERE room_id=? AND user_id=?`).bind(room.id,b.user_id),env.DB.prepare(`UPDATE study_rooms SET owner_id=?,updated_at=? WHERE id=?`).bind(b.user_id,now(),room.id)]);return ok({owner_id:b.user_id})}
  p=match(path,'/api/rooms/:roomId');if(p&&request.method==='PATCH'){const user=requireAuth(ctx),r=await first(env.DB,`SELECT * FROM study_rooms WHERE id=?`,p.roomId);if(!r||(r.owner_id!==user.id&&user.role!=='MANAGER'))return fail('FORBIDDEN','Host access required',403,requestId);const b=await jsonBody(request),status=b.status?oneOf(b.status,['Open','Closed','Completed'],'status'):r.status;if(r.status==='Completed'&&status!=='Completed'&&user.role!=='MANAGER')return fail('INVALID_TRANSITION','Completed rooms are terminal',409,requestId);await env.DB.prepare(`UPDATE study_rooms SET name=?,topic=?,description=?,starts_at=?,duration_minutes=?,capacity=?,visibility=?,status=?,updated_at=? WHERE id=?`).bind(b.name??r.name,b.topic??r.topic,b.description??r.description,b.starts_at??r.starts_at,b.duration_minutes??r.duration_minutes,b.capacity??r.capacity,b.visibility??r.visibility,status,now(),r.id).run();return ok(await first(env.DB,`SELECT * FROM study_rooms WHERE id=?`,r.id))}
  if(p&&request.method==='DELETE'){const user=requireAuth(ctx),r=await first(env.DB,`SELECT * FROM study_rooms WHERE id=?`,p.roomId);if(!r||(r.owner_id!==user.id&&user.role!=='MANAGER'))return fail('FORBIDDEN','Host access required',403,requestId);await env.DB.prepare(`DELETE FROM study_rooms WHERE id=?`).bind(r.id).run();if(user.role==='MANAGER')await audit(env,ctx,'room.delete','room',r.id,r.owner_id);return new Response(null,{status:204})}

  p=match(path,'/api/opportunities/:opportunityId');if(p&&request.method==='PATCH'){requireManager(ctx);const r=await first(env.DB,`SELECT * FROM opportunities WHERE id=?`,p.opportunityId);if(!r)return fail('NOT_FOUND','Opportunity not found',404,requestId);const b=await jsonBody(request),publish=!r.published&&b.published===true;await env.DB.prepare(`UPDATE opportunities SET title_en=?,title_ar=?,organization=?,description_en=?,description_ar=?,eligibility_en=?,eligibility_ar=?,skills=?,location=?,mode=?,level=?,deadline=?,application_url=?,published=?,published_at=?,updated_at=? WHERE id=?`).bind(b.title_en??r.title_en,b.title_ar??r.title_ar,b.organization??r.organization,b.description_en??r.description_en,b.description_ar??r.description_ar,b.eligibility_en??r.eligibility_en,b.eligibility_ar??r.eligibility_ar,b.skills?JSON.stringify(b.skills):r.skills,b.location??r.location,b.mode??r.mode,b.level??r.level,b.deadline??r.deadline,b.application_url?safeUrl(b.application_url,'application_url'):r.application_url,'published'in b?(b.published?1:0):r.published,publish?now():r.published_at,now(),r.id).run();await audit(env,ctx,'opportunity.update','opportunity',r.id);return ok(await first(env.DB,`SELECT * FROM opportunities WHERE id=?`,r.id))}
  if(p&&request.method==='DELETE'){requireManager(ctx);await env.DB.prepare(`DELETE FROM opportunities WHERE id=?`).bind(p.opportunityId).run();await audit(env,ctx,'opportunity.delete','opportunity',p.opportunityId);return new Response(null,{status:204})}

  for(const [suffix,table,order] of [['progress','lecture_progress','updated_at DESC'],['degrees','degree_records','recorded_at DESC'],['schedule','schedule_items','starts_at DESC'],['activity','study_activity','occurred_at DESC']]){p=match(path,`/api/manager/students/:userId/${suffix}`);if(p&&request.method==='GET'){requireManager(ctx);const courseId=url.searchParams.get('courseId');if(!courseId)return fail('COURSE_REQUIRED','courseId is required',422,requestId);return collection(await all(env.DB,`SELECT * FROM ${table} WHERE user_id=? AND course_id=? ORDER BY ${order} LIMIT 250`,p.userId,courseId))}}
  p=match(path,'/api/manager/students/:userId/schedule');if(p&&request.method==='POST'){const manager=requireManager(ctx),b=await jsonBody(request),courseId=b.course_id;if(!await first(env.DB,`SELECT 1 ok FROM course_enrollments WHERE user_id=? AND course_id=?`,p.userId,courseId))return fail('NOT_ENROLLED','Student is not enrolled in the selected course',409,requestId);const sid=id('sch');await env.DB.prepare(`INSERT INTO schedule_items(id,user_id,course_id,title,subject_id,category,starts_at,ends_at,reminder,completed,completed_at,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,0,NULL,?,?,?)`).bind(sid,p.userId,courseId,requireText(b,'title',200),b.subject_id||null,b.category||'study',b.starts_at,b.ends_at,b.reminder?1:0,manager.id,now(),now()).run();await audit(env,ctx,'student.schedule.create','schedule',sid,p.userId,{courseId});return ok(await first(env.DB,`SELECT * FROM schedule_items WHERE id=?`,sid),201)}

  p=match(path,'/api/subjects/:subjectId');if(p&&request.method==='DELETE'){requireManager(ctx);const deps=await first(env.DB,`SELECT (SELECT COUNT(*) FROM lectures WHERE subject_id=?) lectures,(SELECT COUNT(*) FROM degree_records WHERE subject_id=?) degrees,(SELECT COUNT(*) FROM study_activity WHERE subject_id=?) activity`,p.subjectId,p.subjectId,p.subjectId);if((deps.lectures||0)+(deps.degrees||0)+(deps.activity||0)>0)return fail('SUBJECT_HAS_DEPENDENCIES','Archive or unpublish this subject instead',409,requestId);await env.DB.prepare(`DELETE FROM subjects WHERE id=?`).bind(p.subjectId).run();await audit(env,ctx,'subject.delete','subject',p.subjectId);return new Response(null,{status:204})}
  p=match(path,'/api/lectures/:lectureId');if(p&&request.method==='DELETE'){requireManager(ctx);const deps=await first(env.DB,`SELECT (SELECT COUNT(*) FROM lecture_progress WHERE lecture_id=?) progress,(SELECT COUNT(*) FROM study_activity WHERE lecture_id=?) activity`,p.lectureId,p.lectureId);if((deps.progress||0)+(deps.activity||0)>0)return fail('LECTURE_HAS_DEPENDENCIES','Archive or unpublish this lecture instead',409,requestId);await env.DB.prepare(`DELETE FROM lectures WHERE id=?`).bind(p.lectureId).run();await audit(env,ctx,'lecture.delete','lecture',p.lectureId);return new Response(null,{status:204})}

  return null;
 }catch(error){if(error instanceof ValidationError)return fail('VALIDATION_ERROR',error.message,422,requestId,error.fields);return fail(error.code||'INTERNAL_ERROR',error.status?error.message:'Unexpected server error',error.status||500,requestId)}
}
