import { ok, collection, fail } from './response.js';
import { ValidationError, email, password, requireText, optionalText, oneOf, bool, numberIn, safeUrl, rejectUnknown } from './validation.js';
import { sessionContext, requireAuth, requireManager, requireCourse } from './auth/middleware.js';
import { createSession, authenticate, uniqueUsername, hashPassword, id, now } from './auth/service.js';
import { sessionCookie, clearSessionCookie, assertMutationOrigin } from './security.js';
import { first, all } from './db.js';
import { assertSubjectInCourse } from './course-context.js';

const page = () => ({ cursor:null,nextCursor:null,hasMore:false });
const userSummary = u => ({ id:u.id, username:u.username, full_name:u.full_name, role:u.role, streak:u.streak, status:u.status });
const parseJson = async request => { const type=request.headers.get('content-type')||''; if(!type.includes('application/json')) throw Object.assign(new Error('JSON body required'),{status:400,code:'JSON_REQUIRED'}); try{return await request.json();}catch{throw Object.assign(new Error('Malformed JSON'),{status:400,code:'MALFORMED_JSON'});} };
const route = (pathname, pattern) => { const keys=[]; const regex=new RegExp('^'+pattern.replace(/:[^/]+/g,t=>{keys.push(t.slice(1));return '([^/]+)'})+'$'); const match=pathname.match(regex); return match?Object.fromEntries(keys.map((k,i)=>[k,decodeURIComponent(match[i+1])])):null; };
const bodyText = row => row ? { ...row, skills: row.skills ? safeJson(row.skills,[]) : row.skills } : row;
const safeJson = (value,fallback={}) => { try{return JSON.parse(value)}catch{return fallback} };
async function audit(env, ctx, action, kind, entityId, targetUserId=null, metadata={}) { await env.DB.prepare(`INSERT INTO audit_events(id,actor_user_id,target_user_id,action,entity_kind,entity_id,course_id,metadata,request_id,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)`).bind(id('aud'),ctx.user?.id||null,targetUserId,action,kind,entityId,ctx.activeCourse?.id||null,JSON.stringify(metadata),ctx.requestId,now()).run(); }
async function settings(env,userId){ return first(env.DB,`SELECT * FROM account_settings WHERE user_id=?`,userId); }
async function createNotification(env,{userId,category,event,title,body,path=null,sourceType=null,sourceId=null,dedupeKey=null,preference=null}){ const s=await settings(env,userId); if(preference && !s?.[preference]) return null; const nid=id('ntf'); try{ await env.DB.prepare(`INSERT INTO notifications(id,user_id,category,event,title,body,path,source_type,source_id,dedupe_key,read,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,0,?)`).bind(nid,userId,category,event,title,body,path,sourceType,sourceId,dedupeKey,now()).run(); return nid; }catch(e){ if(String(e.message).includes('UNIQUE')) return null; throw e; } }

export async function handleApi(request, env) {
  const requestId=crypto.randomUUID(); const url=new URL(request.url); const path=url.pathname; const ctx={...(await sessionContext(request,env)),requestId};
  try{
    assertMutationOrigin(request);

    if(path==='/api/auth/me' && request.method==='GET'){ if(!ctx.user)return fail('UNAUTHENTICATED','No active session',401,requestId); return ok({user:userSummary(ctx.user),activeCourse:ctx.activeCourse}); }
    if(path==='/api/auth/signin' && request.method==='POST'){ const b=await parseJson(request); rejectUnknown(b,['email','password']); const em=email(b.email); const pw=password(b.password); const user=await authenticate(env.DB,em,pw); if(!user)return fail('INVALID_CREDENTIALS','Invalid email or password',401,requestId); const token=await createSession(env.DB,user.id); await env.DB.prepare(`UPDATE accounts SET last_login_at=?,updated_at=? WHERE id=?`).bind(now(),now(),user.id).run(); return new Response(JSON.stringify({data:{user:userSummary(user)}}),{status:200,headers:{'content-type':'application/json','set-cookie':sessionCookie(token),'cache-control':'no-store'}}); }
    if(path==='/api/auth/signout' && request.method==='POST'){ requireAuth(ctx); if(ctx.tokenHash) await env.DB.prepare(`DELETE FROM account_sessions WHERE token_hash=?`).bind(ctx.tokenHash).run(); return new Response(null,{status:204,headers:{'set-cookie':clearSessionCookie()}}); }
    if(path==='/api/auth/signup' && request.method==='POST'){
      const type=request.headers.get('content-type')||''; if(!type.includes('multipart/form-data')) return fail('MULTIPART_REQUIRED','Profile photo is required',400,requestId);
      const form=await request.formData(); const em=email(form.get('email')); const pw=password(form.get('password')); const full=requireText(Object.fromEntries(form),'full_name',120); const stage=requireText(Object.fromEntries(form),'educational_stage',80); const category=oneOf(form.get('institution_category'),['SCHOOL','UNIVERSITY','OTHER'],'institution_category'); const institution=requireText(Object.fromEntries(form),'institution_name',180); const lang=oneOf(form.get('preferred_language')||'en',['en','ar'],'preferred_language'); const photo=form.get('photo'); if(!(photo instanceof File)||!photo.type.startsWith('image/')||photo.size<1||photo.size>5_000_000) throw new ValidationError({photo:'Upload an image up to 5 MB'});
      if(await first(env.DB,`SELECT 1 ok FROM accounts WHERE email=? COLLATE NOCASE`,em)) return fail('EMAIL_IN_USE','An account already uses this email',409,requestId,{email:'Already registered'});
      const uid=id('usr'); const username=await uniqueUsername(env.DB,em); const photoKey=`profile:${uid}`; const created=now(); const course=await first(env.DB,`SELECT * FROM courses WHERE published=1 AND audience='TARGETED' AND (educational_stage IS NULL OR educational_stage=?) AND (institution_category IS NULL OR institution_category=?) AND (institution_name IS NULL OR institution_name=?) ORDER BY created_at LIMIT 1`,stage,category,institution);
      await env.PROFILE_PHOTOS.put(photoKey,await photo.arrayBuffer(),{metadata:{contentType:photo.type}});
      const stmts=[env.DB.prepare(`INSERT INTO accounts(id,email,username,password_hash,role,full_name,bio,learning_goal,streak,status,joined_at,updated_at) VALUES(?,?,?,?, 'STUDENT',?,?,?,0,'ACTIVE',?,?)`).bind(uid,em,username,hashPassword(pw),full,optionalText(Object.fromEntries(form),'bio',500),optionalText(Object.fromEntries(form),'learning_goal',500),created,created),env.DB.prepare(`INSERT INTO account_settings(user_id,preferred_language,updated_at) VALUES(?,?,?)`).bind(uid,lang,created),env.DB.prepare(`INSERT INTO account_academics(user_id,educational_stage,grade,academic_field,college,institution_category,institution_name,country,photo_key,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)`).bind(uid,stage,form.get('grade')||null,form.get('academic_field')||null,form.get('college')||null,category,institution,form.get('country')||null,photoKey,created)];
      if(course) stmts.push(env.DB.prepare(`INSERT INTO course_enrollments(user_id,course_id,position,active,source,enrolled_at,updated_at) VALUES(?,?,1,1,'AUTO',?,?)`).bind(uid,course.id,created,created));
      try{ await env.DB.batch(stmts); }catch(e){ await env.PROFILE_PHOTOS.delete(photoKey); throw e; }
      const token=await createSession(env.DB,uid); return new Response(JSON.stringify({data:{user:{id:uid,username,full_name:full,role:'STUDENT'},activeCourse:course||null}}),{status:201,headers:{'content-type':'application/json','set-cookie':sessionCookie(token),'cache-control':'no-store'}});
    }

    if(path==='/api/bootstrap' && request.method==='GET'){
      const user=requireAuth(ctx); const s=await settings(env,user.id); const enrollments=await all(env.DB,`SELECT ce.*,c.name_en,c.name_ar,c.slug FROM course_enrollments ce JOIN courses c ON c.id=ce.course_id WHERE ce.user_id=? ORDER BY ce.position`,user.id); const unread=(await first(env.DB,`SELECT COUNT(*) count FROM notifications WHERE user_id=? AND read=0`,user.id))?.count||0; let summary={};
      if(ctx.activeCourse){ const cid=ctx.activeCourse.id; const counts=await first(env.DB,`SELECT COUNT(DISTINCT cs.subject_id) subjectCount,(SELECT COUNT(*) FROM lectures l JOIN course_subjects cs2 ON cs2.subject_id=l.subject_id WHERE cs2.course_id=? AND l.published=1 AND l.archived=0) lectureCount,(SELECT COUNT(*) FROM lecture_progress lp WHERE lp.user_id=? AND lp.course_id=? AND lp.completed=1) completedLectureCount FROM course_subjects cs JOIN subjects s ON s.id=cs.subject_id WHERE cs.course_id=? AND s.published=1 AND s.archived=0`,cid,user.id,cid,cid); const avg=await first(env.DB,`SELECT CASE WHEN SUM(max_score)>0 THEN SUM(score)*100.0/SUM(max_score) ELSE 0 END academicAverage FROM degree_records WHERE user_id=? AND course_id=?`,user.id,cid); const study=await first(env.DB,`SELECT COALESCE(SUM(minutes),0) studyMinutesWeek FROM study_activity WHERE user_id=? AND course_id=? AND occurred_at>=?`,user.id,cid,new Date(Date.now()-7*86400000).toISOString()); const next=await all(env.DB,`SELECT l.*,s.name_en subject_name_en,s.name_ar subject_name_ar FROM lectures l JOIN subjects s ON s.id=l.subject_id JOIN course_subjects cs ON cs.subject_id=s.id LEFT JOIN lecture_progress lp ON lp.lecture_id=l.id AND lp.user_id=? AND lp.course_id=? WHERE cs.course_id=? AND l.published=1 AND l.archived=0 AND COALESCE(lp.completed,0)=0 ORDER BY COALESCE(lp.bookmarked,0) DESC,l.sort_order LIMIT 4`,user.id,cid,cid); const upcoming=await all(env.DB,`SELECT * FROM schedule_items WHERE user_id=? AND course_id=? AND completed=0 AND starts_at>=? ORDER BY starts_at LIMIT 4`,user.id,cid,now()); summary={...counts,...avg,...study,lectureProgressPercent:counts?.lectureCount?((counts.completedLectureCount||0)*100/counts.lectureCount):0,continueLearning:next,upcomingSchedule:upcoming}; }
      return ok({user:userSummary(user),settings:s,enrollments,activeCourse:ctx.activeCourse,activeCourseSummary:summary,dashboard:summary,notificationUnreadCount:unread,permissions:user.role==='MANAGER'?['manage_catalog','manage_assessments','moderate','manage_opportunities','manage_users','view_audit']:[]});
    }

    if(path==='/api/profile' && request.method==='GET'){ const user=requireAuth(ctx); const data=await first(env.DB,`SELECT a.id,a.username,a.full_name,a.bio,a.learning_goal,a.streak,a.joined_at,aa.educational_stage,aa.grade,aa.academic_field,aa.college,aa.institution_category,aa.institution_name,aa.country FROM accounts a JOIN account_academics aa ON aa.user_id=a.id WHERE a.id=?`,user.id); return ok(data); }
    if(path==='/api/profile' && request.method==='PATCH'){ const user=requireAuth(ctx); const b=await parseJson(request); rejectUnknown(b,['full_name','username','bio','learning_goal','educational_stage','grade','academic_field','college','institution_category','institution_name','country']); const fields=[]; const vals=[]; for(const k of ['full_name','username','bio','learning_goal']) if(k in b){fields.push(`${k}=?`);vals.push(k==='full_name'?requireText(b,k,120):k==='username'?requireText(b,k,40):optionalText(b,k,500));} if(fields.length) await env.DB.prepare(`UPDATE accounts SET ${fields.join(',')},updated_at=? WHERE id=?`).bind(...vals,now(),user.id).run(); const af=[]; const av=[]; for(const k of ['educational_stage','grade','academic_field','college','institution_category','institution_name','country']) if(k in b){af.push(`${k}=?`);av.push(b[k]||null);} if(af.length) await env.DB.prepare(`UPDATE account_academics SET ${af.join(',')},updated_at=? WHERE user_id=?`).bind(...av,now(),user.id).run(); return ok((await first(env.DB,`SELECT id,username,full_name,bio,learning_goal FROM accounts WHERE id=?`,user.id))); }
    if(path==='/api/profile/photo' && request.method==='PUT'){ const user=requireAuth(ctx); const blob=await request.blob(); if(!blob.type.startsWith('image/')||blob.size>5_000_000)throw new ValidationError({photo:'Upload an image up to 5 MB'}); const profile=await first(env.DB,`SELECT photo_key FROM account_academics WHERE user_id=?`,user.id); await env.PROFILE_PHOTOS.put(profile.photo_key,blob,{metadata:{contentType:blob.type}}); return ok({updated:true}); }
    const photoRoute=route(path,'/api/profile-photo/:userId'); if(photoRoute && request.method==='GET'){ requireAuth(ctx); const profile=await first(env.DB,`SELECT photo_key FROM account_academics WHERE user_id=?`,photoRoute.userId); if(!profile)return fail('NOT_FOUND','Profile not found',404,requestId); const object=await env.PROFILE_PHOTOS.get(profile.photo_key); if(!object)return fail('NOT_FOUND','Photo not found',404,requestId); return new Response(object.body,{headers:{'content-type':object.metadata?.contentType||'image/jpeg','cache-control':'private, max-age=3600'}}); }
    const publicProfile=route(path,'/api/users/:userId/profile'); if(publicProfile&&request.method==='GET'){ const user=requireAuth(ctx); const target=await first(env.DB,`SELECT a.id,a.username,a.full_name,a.bio,a.learning_goal,a.streak,a.role,s.profile_visibility FROM accounts a JOIN account_settings s ON s.user_id=a.id WHERE a.id=?`,publicProfile.userId); if(!target)return fail('NOT_FOUND','Profile not found',404,requestId); if(target.profile_visibility==='private'&&user.id!==target.id&&user.role!=='MANAGER')return fail('NOT_FOUND','Profile not found',404,requestId); if(target.profile_visibility==='classmates'&&user.id!==target.id&&user.role!=='MANAGER'){ const shared=await first(env.DB,`SELECT 1 ok FROM course_enrollments a JOIN course_enrollments b ON b.course_id=a.course_id WHERE a.user_id=? AND b.user_id=? LIMIT 1`,user.id,target.id); if(!shared)return fail('NOT_FOUND','Profile not found',404,requestId);} delete target.profile_visibility; return ok(target); }
    if(path==='/api/settings'&&request.method==='GET'){ const user=requireAuth(ctx); return ok(await settings(env,user.id)); }
    if(path==='/api/settings'&&request.method==='PATCH'){ const user=requireAuth(ctx); const b=await parseJson(request); const allowed=['preferred_language','study_reminders','scholarship_alerts','job_alerts','volunteer_alerts','community_notifications','room_notifications','profile_visibility']; rejectUnknown(b,allowed); const sets=[];const vals=[]; for(const [k,v] of Object.entries(b)){ sets.push(`${k}=?`); if(k==='preferred_language')vals.push(oneOf(v,['en','ar'],k)); else if(k==='profile_visibility')vals.push(oneOf(v,['everyone','classmates','private'],k)); else vals.push(bool(v,k)?1:0); } if(!sets.length)return ok(await settings(env,user.id)); await env.DB.prepare(`UPDATE account_settings SET ${sets.join(',')},updated_at=? WHERE user_id=?`).bind(...vals,now(),user.id).run(); return ok(await settings(env,user.id)); }
    if(path==='/api/account/password'&&request.method==='PATCH'){ const user=requireAuth(ctx); const b=await parseJson(request); rejectUnknown(b,['current_password','new_password']); const current=password(b.current_password); const next=password(b.new_password); const auth=await authenticate(env.DB,user.email,current); if(!auth)return fail('INVALID_PASSWORD','Current password is incorrect',403,requestId); await env.DB.batch([env.DB.prepare(`UPDATE accounts SET password_hash=?,updated_at=? WHERE id=?`).bind(hashPassword(next),now(),user.id),env.DB.prepare(`DELETE FROM account_sessions WHERE user_id=?`).bind(user.id)]); const token=await createSession(env.DB,user.id); return new Response(JSON.stringify({data:{changed:true}}),{headers:{'content-type':'application/json','set-cookie':sessionCookie(token),'cache-control':'no-store'}}); }

    if(path==='/api/courses'&&request.method==='GET'){ const user=requireAuth(ctx); const enrollments=await all(env.DB,`SELECT ce.*,c.* FROM course_enrollments ce JOIN courses c ON c.id=ce.course_id WHERE ce.user_id=? ORDER BY ce.position`,user.id); const available=await all(env.DB,`SELECT * FROM courses c WHERE c.published=1 AND c.audience='PUBLIC' AND NOT EXISTS(SELECT 1 FROM course_enrollments ce WHERE ce.user_id=? AND ce.course_id=c.id) ORDER BY c.name_en LIMIT 30`,user.id); return ok({enrollments,available,remainingOptionalPositions:Math.max(0,3-enrollments.length),activeCourse:ctx.activeCourse}); }
    const enroll=route(path,'/api/courses/:courseId/enroll'); if(enroll&&request.method==='POST'){ const user=requireAuth(ctx); const course=await first(env.DB,`SELECT * FROM courses WHERE id=? AND published=1 AND audience='PUBLIC'`,enroll.courseId); if(!course)return fail('NOT_ENROLLABLE','Course is not available for self-enrollment',404,requestId); if(await first(env.DB,`SELECT 1 ok FROM course_enrollments WHERE user_id=? AND course_id=?`,user.id,course.id))return fail('ALREADY_ENROLLED','Already enrolled',409,requestId); const rows=await all(env.DB,`SELECT position FROM course_enrollments WHERE user_id=?`,user.id); const used=new Set(rows.map(r=>r.position)); const position=[2,3].find(p=>!used.has(p)); if(!position)return fail('ENROLLMENT_LIMIT','Maximum of three courses reached',409,requestId); await env.DB.prepare(`INSERT INTO course_enrollments(user_id,course_id,position,active,source,enrolled_at,updated_at) VALUES(?,?,?,0,'SELF',?,?)`).bind(user.id,course.id,position,now(),now()).run(); return ok({courseId:course.id,position,active:false},201); }
    const activate=route(path,'/api/courses/:courseId/activate'); if(activate&&request.method==='POST'){ const user=requireAuth(ctx); if(!await first(env.DB,`SELECT 1 ok FROM course_enrollments WHERE user_id=? AND course_id=?`,user.id,activate.courseId))return fail('NOT_ENROLLED','Not enrolled in that course',404,requestId); await env.DB.batch([env.DB.prepare(`UPDATE course_enrollments SET active=0,updated_at=? WHERE user_id=?`).bind(now(),user.id),env.DB.prepare(`UPDATE course_enrollments SET active=1,updated_at=? WHERE user_id=? AND course_id=?`).bind(now(),user.id,activate.courseId)]); return ok({activeCourseId:activate.courseId}); }
    if(enroll&&request.method==='DELETE'){ const user=requireAuth(ctx); const row=await first(env.DB,`SELECT * FROM course_enrollments WHERE user_id=? AND course_id=?`,user.id,enroll.courseId); if(!row)return fail('NOT_ENROLLED','Enrollment not found',404,requestId); if(row.position===1)return fail('PRIMARY_COURSE_REQUIRED','Primary course cannot be removed',409,requestId); let replacement=null; try{replacement=(await request.json()).replacementCourseId}catch{} if(row.active){ if(!replacement)return fail('ACTIVE_COURSE_REPLACEMENT_REQUIRED','Activate another course before removing this one',409,requestId); if(!await first(env.DB,`SELECT 1 ok FROM course_enrollments WHERE user_id=? AND course_id=?`,user.id,replacement))return fail('INVALID_REPLACEMENT','Replacement course is not enrolled',409,requestId); await env.DB.batch([env.DB.prepare(`UPDATE course_enrollments SET active=0 WHERE user_id=?`).bind(user.id),env.DB.prepare(`UPDATE course_enrollments SET active=1,updated_at=? WHERE user_id=? AND course_id=?`).bind(now(),user.id,replacement),env.DB.prepare(`DELETE FROM course_enrollments WHERE user_id=? AND course_id=?`).bind(user.id,row.course_id)]); }else await env.DB.prepare(`DELETE FROM course_enrollments WHERE user_id=? AND course_id=?`).bind(user.id,row.course_id).run(); return new Response(null,{status:204}); }
    if(path==='/api/courses'&&request.method==='POST'){ requireManager(ctx); const b=await parseJson(request); const cid=id('crs'); const audience=oneOf(b.audience,['TARGETED','PUBLIC'],'audience'); await env.DB.prepare(`INSERT INTO courses(id,slug,name_en,name_ar,description_en,description_ar,audience,educational_stage,grade,academic_field,college,institution_category,institution_name,published,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(cid,requireText(b,'slug',100),requireText(b,'name_en',180),requireText(b,'name_ar',180),optionalText(b,'description_en',4000),optionalText(b,'description_ar',4000),audience,b.educational_stage||null,b.grade||null,b.academic_field||null,b.college||null,b.institution_category||null,b.institution_name||null,b.published?1:0,now(),now()).run(); await audit(env,ctx,'course.create','course',cid); return ok(await first(env.DB,`SELECT * FROM courses WHERE id=?`,cid),201); }
    const coursePatch=route(path,'/api/courses/:courseId'); if(coursePatch&&request.method==='PATCH'){ requireManager(ctx); const b=await parseJson(request); const fields=[];const vals=[];for(const k of ['name_en','name_ar','description_en','description_ar','published'])if(k in b){fields.push(`${k}=?`);vals.push(k==='published'?(b[k]?1:0):b[k]);} if(fields.length)await env.DB.prepare(`UPDATE courses SET ${fields.join(',')},updated_at=? WHERE id=?`).bind(...vals,now(),coursePatch.courseId).run(); await audit(env,ctx,'course.update','course',coursePatch.courseId); return ok(await first(env.DB,`SELECT * FROM courses WHERE id=?`,coursePatch.courseId)); }

    if(path==='/api/subjects'&&request.method==='GET'){ const user=requireAuth(ctx); const course=requireCourse(ctx); const q=(url.searchParams.get('q')||'').trim(); const rows=await all(env.DB,`SELECT s.*,(SELECT COUNT(*) FROM lectures l WHERE l.subject_id=s.id AND l.published=1 AND l.archived=0) lecture_count,(SELECT COUNT(*) FROM lecture_progress lp WHERE lp.user_id=? AND lp.course_id=? AND lp.subject_id=s.id AND lp.completed=1) completed_lecture_count FROM course_subjects cs JOIN subjects s ON s.id=cs.subject_id WHERE cs.course_id=? AND s.published=1 AND s.archived=0 AND (?='' OR lower(s.name_en) LIKE lower(?) OR lower(s.name_ar) LIKE lower(?) OR lower(COALESCE(s.code,'')) LIKE lower(?)) ORDER BY cs.sort_order,s.name_en LIMIT 100`,user.id,course.id,course.id,q,`%${q}%`,`%${q}%`,`%${q}%`); rows.forEach(r=>r.progress_percentage=r.lecture_count?Math.round(r.completed_lecture_count*100/r.lecture_count):0); return collection(rows,page()); }
    if(path==='/api/subjects'&&request.method==='POST'){ requireManager(ctx); const b=await parseJson(request); const sid=id('sub'); await env.DB.prepare(`INSERT INTO subjects(id,code,name_en,name_ar,description_en,description_ar,published,archived,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,0,?,?,?)`).bind(sid,b.code||null,requireText(b,'name_en',160),requireText(b,'name_ar',160),optionalText(b,'description_en',4000),optionalText(b,'description_ar',4000),b.published?1:0,ctx.user.id,now(),now()).run(); await audit(env,ctx,'subject.create','subject',sid); return ok(await first(env.DB,`SELECT * FROM subjects WHERE id=?`,sid),201); }
    const subject=route(path,'/api/subjects/:subjectId'); if(subject&&request.method==='GET'){ const course=requireCourse(ctx); await assertSubjectInCourse(env.DB,subject.subjectId,course.id); const row=await first(env.DB,`SELECT * FROM subjects WHERE id=?`,subject.subjectId); if(!row)return fail('NOT_FOUND','Subject not found',404,requestId); return ok(row); }
    if(subject&&request.method==='PATCH'){ requireManager(ctx); const b=await parseJson(request); const fields=[];const vals=[];for(const k of ['code','name_en','name_ar','description_en','description_ar','published','archived'])if(k in b){fields.push(`${k}=?`);vals.push(['published','archived'].includes(k)?(b[k]?1:0):b[k]);} if(fields.length)await env.DB.prepare(`UPDATE subjects SET ${fields.join(',')},updated_at=? WHERE id=?`).bind(...vals,now(),subject.subjectId).run(); await audit(env,ctx,'subject.update','subject',subject.subjectId); return ok(await first(env.DB,`SELECT * FROM subjects WHERE id=?`,subject.subjectId)); }
    const lectureList=route(path,'/api/subjects/:subjectId/lectures'); if(lectureList&&request.method==='GET'){ const course=requireCourse(ctx); await assertSubjectInCourse(env.DB,lectureList.subjectId,course.id); return collection(await all(env.DB,`SELECT l.*,COALESCE(lp.completed,0) completed,COALESCE(lp.bookmarked,0) bookmarked FROM lectures l LEFT JOIN lecture_progress lp ON lp.lecture_id=l.id AND lp.user_id=? AND lp.course_id=? WHERE l.subject_id=? AND l.published=1 AND l.archived=0 ORDER BY l.sort_order,l.created_at`,ctx.user.id,course.id,lectureList.subjectId)); }
    if(lectureList&&request.method==='POST'){ requireManager(ctx); const b=await parseJson(request); const lid=id('lec'); await env.DB.prepare(`INSERT INTO lectures(id,subject_id,title_en,title_ar,content_en,content_ar,estimated_minutes,sort_order,published,archived,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,0,?,?,?)`).bind(lid,lectureList.subjectId,requireText(b,'title_en',200),requireText(b,'title_ar',200),optionalText(b,'content_en',50000),optionalText(b,'content_ar',50000),numberIn(b.estimated_minutes||0,0,1440,'estimated_minutes'),Number(b.sort_order||0),b.published?1:0,ctx.user.id,now(),now()).run(); await audit(env,ctx,'lecture.create','lecture',lid); return ok(await first(env.DB,`SELECT * FROM lectures WHERE id=?`,lid),201); }
    const lecture=route(path,'/api/lectures/:lectureId'); if(lecture&&request.method==='GET'){ const course=requireCourse(ctx); const row=await first(env.DB,`SELECT l.*,s.name_en subject_name_en,s.name_ar subject_name_ar,COALESCE(lp.completed,0) completed,COALESCE(lp.bookmarked,0) bookmarked FROM lectures l JOIN subjects s ON s.id=l.subject_id JOIN course_subjects cs ON cs.subject_id=s.id LEFT JOIN lecture_progress lp ON lp.lecture_id=l.id AND lp.user_id=? AND lp.course_id=? WHERE l.id=? AND cs.course_id=? AND l.published=1 AND l.archived=0`,ctx.user.id,course.id,lecture.lectureId,course.id); if(!row)return fail('NOT_FOUND','Lecture not found',404,requestId); row.resources=await all(env.DB,`SELECT * FROM lecture_resources WHERE lecture_id=? ORDER BY sort_order`,row.id); return ok(row); }
    if(lecture&&request.method==='PATCH'){ requireManager(ctx); const b=await parseJson(request); const fields=[];const vals=[];for(const k of ['title_en','title_ar','content_en','content_ar','estimated_minutes','sort_order','published','archived'])if(k in b){fields.push(`${k}=?`);vals.push(['published','archived'].includes(k)?(b[k]?1:0):b[k]);} if(fields.length)await env.DB.prepare(`UPDATE lectures SET ${fields.join(',')},updated_at=? WHERE id=?`).bind(...vals,now(),lecture.lectureId).run(); await audit(env,ctx,'lecture.update','lecture',lecture.lectureId); return ok(await first(env.DB,`SELECT * FROM lectures WHERE id=?`,lecture.lectureId)); }
    const progress=route(path,'/api/lectures/:lectureId/progress'); if(progress&&request.method==='GET'){ const user=requireAuth(ctx),course=requireCourse(ctx); const lectureRow=await first(env.DB,`SELECT l.subject_id FROM lectures l JOIN course_subjects cs ON cs.subject_id=l.subject_id WHERE l.id=? AND cs.course_id=?`,progress.lectureId,course.id); if(!lectureRow)return fail('NOT_FOUND','Lecture not found',404,requestId); return ok((await first(env.DB,`SELECT * FROM lecture_progress WHERE user_id=? AND lecture_id=? AND course_id=?`,user.id,progress.lectureId,course.id))||{user_id:user.id,lecture_id:progress.lectureId,course_id:course.id,subject_id:lectureRow.subject_id,completed:0,bookmarked:0}); }
    if(progress&&request.method==='PATCH'){ const user=requireAuth(ctx),course=requireCourse(ctx); const b=await parseJson(request); rejectUnknown(b,['completed','bookmarked']); const lr=await first(env.DB,`SELECT l.subject_id FROM lectures l JOIN course_subjects cs ON cs.subject_id=l.subject_id WHERE l.id=? AND cs.course_id=?`,progress.lectureId,course.id); if(!lr)return fail('NOT_FOUND','Lecture not found',404,requestId); const old=await first(env.DB,`SELECT * FROM lecture_progress WHERE user_id=? AND lecture_id=? AND course_id=?`,user.id,progress.lectureId,course.id); const completed='completed'in b?(bool(b.completed,'completed')?1:0):(old?.completed||0); const bookmarked='bookmarked'in b?(bool(b.bookmarked,'bookmarked')?1:0):(old?.bookmarked||0); const completedAt=completed?(old?.completed_at||now()):null; await env.DB.prepare(`INSERT INTO lecture_progress(user_id,lecture_id,subject_id,course_id,completed,bookmarked,completed_at,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(user_id,lecture_id,course_id) DO UPDATE SET completed=excluded.completed,bookmarked=excluded.bookmarked,completed_at=excluded.completed_at,updated_at=excluded.updated_at`).bind(user.id,progress.lectureId,lr.subject_id,course.id,completed,bookmarked,completedAt,now()).run(); return ok(await first(env.DB,`SELECT * FROM lecture_progress WHERE user_id=? AND lecture_id=? AND course_id=?`,user.id,progress.lectureId,course.id)); }
    if(path==='/api/study-activity'&&request.method==='POST'){ const user=requireAuth(ctx),course=requireCourse(ctx); const b=await parseJson(request); await assertSubjectInCourse(env.DB,b.subject_id,course.id); const aid=id('act'); await env.DB.prepare(`INSERT INTO study_activity(id,user_id,course_id,subject_id,lecture_id,schedule_id,activity_kind,minutes,occurred_at,created_at) VALUES(?,?,?,?,?,NULL,?,?,?,?)`).bind(aid,user.id,course.id,b.subject_id,b.lecture_id||null,requireText({activity_kind:b.activity_type||b.activity_kind},'activity_kind',60),numberIn(b.minutes,1,1440,'minutes'),now(),now()).run(); return ok({id:aid},201); }

    if(path==='/api/schedule'&&request.method==='GET'){ const user=requireAuth(ctx),course=requireCourse(ctx); return collection(await all(env.DB,`SELECT * FROM schedule_items WHERE user_id=? AND course_id=? ORDER BY starts_at LIMIT 200`,user.id,course.id)); }
    if(path==='/api/schedule'&&request.method==='POST'){ const user=requireAuth(ctx),course=requireCourse(ctx); const b=await parseJson(request); const start=new Date(b.starts_at),end=new Date(b.ends_at); if(!Number.isFinite(start.getTime())||!Number.isFinite(end.getTime())||end<=start)throw new ValidationError({ends_at:'End must be after start'}); if(b.subject_id)await assertSubjectInCourse(env.DB,b.subject_id,course.id); const sid=id('sch'); await env.DB.prepare(`INSERT INTO schedule_items(id,user_id,course_id,title,subject_id,category,starts_at,ends_at,reminder,completed,completed_at,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,0,NULL,?,?,?)`).bind(sid,user.id,course.id,requireText(b,'title',200),b.subject_id||null,b.category||'study',start.toISOString(),end.toISOString(),b.reminder?1:0,user.id,now(),now()).run(); return ok(await first(env.DB,`SELECT * FROM schedule_items WHERE id=?`,sid),201); }
    const schedule=route(path,'/api/schedule/:itemId'); if(schedule&&request.method==='PATCH'){ const user=requireAuth(ctx); const row=await first(env.DB,`SELECT * FROM schedule_items WHERE id=? AND user_id=?`,schedule.itemId,user.id); if(!row)return fail('NOT_FOUND','Schedule item not found',404,requestId); const b=await parseJson(request); const was=!!row.completed; const completed='completed'in b?bool(b.completed,'completed'):was; const fields=[];const vals=[];for(const k of ['title','category','starts_at','ends_at','reminder'])if(k in b){fields.push(`${k}=?`);vals.push(k==='reminder'?(b[k]?1:0):b[k]);} if('completed'in b){fields.push('completed=?','completed_at=?');vals.push(completed?1:0,completed?now():null);} if(fields.length)await env.DB.prepare(`UPDATE schedule_items SET ${fields.join(',')},updated_at=? WHERE id=?`).bind(...vals,now(),row.id).run(); if(!was&&completed&&row.subject_id){ const mins=Math.max(1,Math.round((new Date(row.ends_at)-new Date(row.starts_at))/60000)); await env.DB.prepare(`INSERT OR IGNORE INTO study_activity(id,user_id,course_id,subject_id,lecture_id,schedule_id,activity_kind,minutes,occurred_at,created_at) VALUES(?,?,?,?,NULL,?,'schedule_completion',?,?,?)`).bind(id('act'),user.id,row.course_id,row.subject_id,row.id,mins,now(),now()).run(); } if(was&&!completed)await env.DB.prepare(`DELETE FROM study_activity WHERE schedule_id=? AND activity_kind='schedule_completion'`).bind(row.id).run(); return ok(await first(env.DB,`SELECT * FROM schedule_items WHERE id=?`,row.id)); }
    if(schedule&&request.method==='DELETE'){ const user=requireAuth(ctx); const row=await first(env.DB,`SELECT 1 ok FROM schedule_items WHERE id=? AND user_id=?`,schedule.itemId,user.id); if(!row)return fail('NOT_FOUND','Schedule item not found',404,requestId); await env.DB.prepare(`DELETE FROM schedule_items WHERE id=?`).bind(schedule.itemId).run(); return new Response(null,{status:204}); }

    if(path==='/api/posts'&&request.method==='GET'){ const user=requireAuth(ctx),course=requireCourse(ctx); const q=(url.searchParams.get('q')||'').trim(); const rows=await all(env.DB,`SELECT p.*,a.id author_id,a.full_name author_full_name,a.username author_username,(SELECT COUNT(*) FROM community_comments c WHERE c.post_id=p.id) comment_count,(SELECT reaction FROM community_reactions r WHERE r.post_id=p.id AND r.user_id=?) my_reaction,EXISTS(SELECT 1 FROM community_saves s WHERE s.post_id=p.id AND s.user_id=?) saved FROM community_posts p JOIN accounts a ON a.id=p.user_id WHERE p.course_id=? AND (?='' OR lower(p.title) LIKE lower(?) OR lower(p.body) LIKE lower(?)) ORDER BY p.pinned DESC,p.created_at DESC LIMIT 100`,user.id,user.id,course.id,q,`%${q}%`,`%${q}%`); rows.forEach(r=>{r.author={id:r.author_id,full_name:r.author_full_name,username:r.author_username};delete r.author_id;delete r.author_full_name;delete r.author_username;}); return collection(rows); }
    if(path==='/api/posts'&&request.method==='POST'){ const user=requireAuth(ctx),course=requireCourse(ctx); const b=await parseJson(request); rejectUnknown(b,['title','body','category','subject_id']); if(b.subject_id)await assertSubjectInCourse(env.DB,b.subject_id,course.id); const pid=id('post'); await env.DB.prepare(`INSERT INTO community_posts(id,user_id,course_id,subject_id,category,title,body,pinned,locked,created_at,updated_at) VALUES(?,?,?,?,?,?,?,0,0,?,?)`).bind(pid,user.id,course.id,b.subject_id||null,oneOf(b.category,['Question','Study tip','Resource','Discussion'],'category'),requireText(b,'title',200),requireText(b,'body',10000),now(),now()).run(); return ok(await first(env.DB,`SELECT * FROM community_posts WHERE id=?`,pid),201); }
    const postRoute=route(path,'/api/posts/:postId'); if(postRoute&&request.method==='GET'){ const user=requireAuth(ctx),course=requireCourse(ctx); const post=await first(env.DB,`SELECT p.*,a.full_name author_full_name,a.username author_username FROM community_posts p JOIN accounts a ON a.id=p.user_id WHERE p.id=? AND p.course_id=?`,postRoute.postId,course.id); if(!post)return fail('NOT_FOUND','Post not found',404,requestId); post.author={full_name:post.author_full_name,username:post.author_username}; post.comments=await all(env.DB,`SELECT c.*,a.full_name,a.username FROM community_comments c JOIN accounts a ON a.id=c.user_id WHERE c.post_id=? ORDER BY c.created_at LIMIT 50`,post.id); return ok(post); }
    if(postRoute&&request.method==='PATCH'){ const user=requireAuth(ctx); const post=await first(env.DB,`SELECT * FROM community_posts WHERE id=?`,postRoute.postId); if(!post|| (post.user_id!==user.id&&user.role!=='MANAGER'))return fail('NOT_FOUND','Post not found',404,requestId); const b=await parseJson(request); const fields=[];const vals=[];for(const k of ['title','body','category','subject_id','pinned','locked'])if(k in b){if(['pinned','locked'].includes(k)&&user.role!=='MANAGER')continue;fields.push(`${k}=?`);vals.push(['pinned','locked'].includes(k)?(b[k]?1:0):b[k]);} if(fields.length)await env.DB.prepare(`UPDATE community_posts SET ${fields.join(',')},updated_at=? WHERE id=?`).bind(...vals,now(),post.id).run(); if(user.role==='MANAGER')await audit(env,ctx,'post.moderate','post',post.id,post.user_id); return ok(await first(env.DB,`SELECT * FROM community_posts WHERE id=?`,post.id)); }
    if(postRoute&&request.method==='DELETE'){ const user=requireAuth(ctx); const post=await first(env.DB,`SELECT * FROM community_posts WHERE id=?`,postRoute.postId); if(!post||(post.user_id!==user.id&&user.role!=='MANAGER'))return fail('NOT_FOUND','Post not found',404,requestId); await env.DB.prepare(`DELETE FROM community_posts WHERE id=?`).bind(post.id).run(); if(user.role==='MANAGER')await audit(env,ctx,'post.delete','post',post.id,post.user_id); return new Response(null,{status:204}); }
    const react=route(path,'/api/posts/:postId/reactions'); if(react&&request.method==='POST'){ const user=requireAuth(ctx),course=requireCourse(ctx); if(!await first(env.DB,`SELECT 1 ok FROM community_posts WHERE id=? AND course_id=?`,react.postId,course.id))return fail('NOT_FOUND','Post not found',404,requestId); const b=await parseJson(request); const reaction=b.reaction; if(reaction===null){await env.DB.prepare(`DELETE FROM community_reactions WHERE post_id=? AND user_id=?`).bind(react.postId,user.id).run();return ok({reaction:null});} oneOf(reaction,['like','helpful','insightful'],'reaction'); await env.DB.prepare(`INSERT INTO community_reactions(post_id,user_id,reaction,created_at,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(post_id,user_id) DO UPDATE SET reaction=excluded.reaction,updated_at=excluded.updated_at`).bind(react.postId,user.id,reaction,now(),now()).run(); return ok({reaction}); }
    const savePost=route(path,'/api/posts/:postId/save'); if(savePost&&request.method==='POST'){ const user=requireAuth(ctx); const exists=await first(env.DB,`SELECT 1 ok FROM community_saves WHERE post_id=? AND user_id=?`,savePost.postId,user.id); const b=await request.json().catch(()=>({})); const wanted=typeof b.saved==='boolean'?b.saved:!exists; if(wanted&&!exists)await env.DB.prepare(`INSERT INTO community_saves(post_id,user_id,created_at) VALUES(?,?,?)`).bind(savePost.postId,user.id,now()).run(); if(!wanted&&exists)await env.DB.prepare(`DELETE FROM community_saves WHERE post_id=? AND user_id=?`).bind(savePost.postId,user.id).run(); return ok({saved:wanted}); }
    const comments=route(path,'/api/posts/:postId/comments'); if(comments&&request.method==='POST'){ const user=requireAuth(ctx),course=requireCourse(ctx); const post=await first(env.DB,`SELECT * FROM community_posts WHERE id=? AND course_id=?`,comments.postId,course.id); if(!post)return fail('NOT_FOUND','Post not found',404,requestId); if(post.locked)return fail('POST_LOCKED','This post is locked',409,requestId); const b=await parseJson(request); const cid=id('com'); await env.DB.prepare(`INSERT INTO community_comments(id,post_id,user_id,body,created_at,updated_at) VALUES(?,?,?,?,?,?)`).bind(cid,post.id,user.id,requireText(b,'body',5000),now(),now()).run(); if(post.user_id!==user.id)await createNotification(env,{userId:post.user_id,category:'community',event:'post.comment',title:'New comment',body:`${user.full_name} commented on your post`,path:`/community/${post.id}`,sourceType:'comment',sourceId:cid,dedupeKey:`post-comment:${cid}:${post.user_id}`,preference:'community_notifications'}); return ok(await first(env.DB,`SELECT * FROM community_comments WHERE id=?`,cid),201); }
    const report=route(path,'/api/posts/:postId/report'); if(report&&request.method==='POST'){ const user=requireAuth(ctx); const b=await parseJson(request); const rid=id('rpt'); try{await env.DB.prepare(`INSERT INTO community_reports(id,post_id,user_id,reason,details,status,created_at) VALUES(?,?,?,?,?,'Open',?)`).bind(rid,report.postId,user.id,oneOf(b.reason,['Spam','Harassment','Misinformation','Other'],'reason'),optionalText(b,'details',2000),now()).run();}catch(e){if(String(e.message).includes('UNIQUE'))return fail('ALREADY_REPORTED','You already reported this post',409,requestId);throw e;} return ok({id:rid,status:'Open'},201); }

    if(path==='/api/rooms'&&request.method==='GET'){ const user=requireAuth(ctx),course=requireCourse(ctx); const rows=await all(env.DB,`SELECT r.*,(SELECT COUNT(*) FROM room_members m WHERE m.room_id=r.id) member_count,EXISTS(SELECT 1 FROM room_members m WHERE m.room_id=r.id AND m.user_id=?) is_member FROM study_rooms r WHERE r.course_id=? ORDER BY CASE r.status WHEN 'Open' THEN 0 WHEN 'Closed' THEN 1 ELSE 2 END,r.starts_at,r.created_at DESC LIMIT 100`,user.id,course.id); return collection(rows); }
    if(path==='/api/rooms'&&request.method==='POST'){ const user=requireAuth(ctx),course=requireCourse(ctx); const b=await parseJson(request); if(b.subject_id)await assertSubjectInCourse(env.DB,b.subject_id,course.id); const rid=id('room'); const ts=now(); await env.DB.batch([env.DB.prepare(`INSERT INTO study_rooms(id,owner_id,course_id,subject_id,name,topic,description,starts_at,duration_minutes,capacity,visibility,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,'Open',?,?)`).bind(rid,user.id,course.id,b.subject_id||null,requireText(b,'name',160),optionalText(b,'topic',300),optionalText(b,'description',2000),b.starts_at||null,numberIn(b.duration_minutes,15,360,'duration_minutes'),numberIn(b.capacity,2,50,'capacity'),oneOf(b.visibility,['Open','Approval'],'visibility'),ts,ts),env.DB.prepare(`INSERT INTO room_members(room_id,user_id,role,joined_at) VALUES(?,?,'Host',?)`).bind(rid,user.id,ts)]); return ok(await first(env.DB,`SELECT * FROM study_rooms WHERE id=?`,rid),201); }
    const room=route(path,'/api/rooms/:roomId'); if(room&&request.method==='GET'){ const user=requireAuth(ctx),course=requireCourse(ctx); const r=await first(env.DB,`SELECT * FROM study_rooms WHERE id=? AND course_id=?`,room.roomId,course.id); if(!r)return fail('NOT_FOUND','Room not found',404,requestId); r.participants=await all(env.DB,`SELECT a.id,a.full_name,a.username,m.role FROM room_members m JOIN accounts a ON a.id=m.user_id WHERE m.room_id=?`,r.id); r.messages=await all(env.DB,`SELECT m.*,a.full_name,a.username FROM room_messages m JOIN accounts a ON a.id=m.user_id WHERE m.room_id=? ORDER BY m.created_at LIMIT 50`,r.id); r.resources=await all(env.DB,`SELECT * FROM room_resources WHERE room_id=? ORDER BY created_at`,r.id); r.tasks=await all(env.DB,`SELECT t.*,EXISTS(SELECT 1 FROM room_task_completions c WHERE c.task_id=t.id AND c.user_id=?) completed FROM room_tasks t WHERE t.room_id=? ORDER BY t.due_at`,user.id,r.id); return ok(r); }
    const join=route(path,'/api/rooms/:roomId/join'); if(join&&request.method==='POST'){ const user=requireAuth(ctx),course=requireCourse(ctx); const r=await first(env.DB,`SELECT * FROM study_rooms WHERE id=? AND course_id=?`,join.roomId,course.id); if(!r)return fail('NOT_FOUND','Room not found',404,requestId); if(r.owner_id===user.id)return fail('HOST_CANNOT_LEAVE','Transfer host ownership first',409,requestId); const member=await first(env.DB,`SELECT * FROM room_members WHERE room_id=? AND user_id=?`,r.id,user.id); if(member){await env.DB.prepare(`DELETE FROM room_members WHERE room_id=? AND user_id=?`).bind(r.id,user.id).run();return ok({membership:'none'});} if(r.status!=='Open')return fail('ROOM_NOT_JOINABLE','Room is not open',409,requestId); const count=(await first(env.DB,`SELECT COUNT(*) count FROM room_members WHERE room_id=?`,r.id)).count; if(count>=r.capacity)return fail('ROOM_FULL','Room is full',409,requestId); if(r.visibility==='Approval'){ await env.DB.prepare(`INSERT INTO room_join_requests(room_id,user_id,status,created_at,updated_at) VALUES(?,?,'Pending',?,?) ON CONFLICT(room_id,user_id) DO UPDATE SET status='Pending',updated_at=excluded.updated_at`).bind(r.id,user.id,now(),now()).run(); await createNotification(env,{userId:r.owner_id,category:'room',event:'room.request',title:'New room join request',body:`${user.full_name} wants to join ${r.name}`,path:`/study-rooms/${r.id}`,sourceType:'room',sourceId:r.id,dedupeKey:`room-request:${r.id}:${user.id}:${now().slice(0,16)}`,preference:'room_notifications'});return ok({membership:'pending'});} await env.DB.prepare(`INSERT INTO room_members(room_id,user_id,role,joined_at) VALUES(?,?,'Member',?)`).bind(r.id,user.id,now()).run(); return ok({membership:'member'}); }
    const messages=route(path,'/api/rooms/:roomId/messages'); if(messages&&request.method==='POST'){ const user=requireAuth(ctx); const member=await first(env.DB,`SELECT m.role,r.status FROM room_members m JOIN study_rooms r ON r.id=m.room_id WHERE m.room_id=? AND m.user_id=?`,messages.roomId,user.id); if(!member&&user.role!=='MANAGER')return fail('FORBIDDEN','Room membership required',403,requestId); if(member?.status!=='Open')return fail('ROOM_READ_ONLY','Room is read only',409,requestId); const b=await parseJson(request); const kind=b.message_kind||'Message'; if(kind==='Announcement'&&member?.role!=='Host'&&user.role!=='MANAGER')return fail('FORBIDDEN','Only a host can announce',403,requestId); const mid=id('msg'); await env.DB.prepare(`INSERT INTO room_messages(id,room_id,user_id,body,message_kind,created_at,updated_at) VALUES(?,?,?,?,?,?,?)`).bind(mid,messages.roomId,user.id,requireText(b,'body',5000),oneOf(kind,['Message','Announcement'],'message_kind'),now(),now()).run(); return ok(await first(env.DB,`SELECT * FROM room_messages WHERE id=?`,mid),201); }

    if(path==='/api/opportunities'&&request.method==='GET'){ const user=requireAuth(ctx); const category=url.searchParams.get('category'); const rows=await all(env.DB,`SELECT o.*,EXISTS(SELECT 1 FROM saved_opportunities s WHERE s.opportunity_id=o.id AND s.user_id=?) saved FROM opportunities o WHERE o.published=1 AND (? IS NULL OR o.category=?) ORDER BY COALESCE(o.deadline,'9999-12-31'),o.published_at DESC LIMIT 100`,user.id,category,category); return collection(rows.map(bodyText)); }
    if(path==='/api/opportunities'&&request.method==='POST'){ requireManager(ctx); const b=await parseJson(request); const oid=id('opp'); await env.DB.prepare(`INSERT INTO opportunities(id,category,title_en,title_ar,organization,description_en,description_ar,eligibility_en,eligibility_ar,skills,location,mode,level,deadline,application_url,published,published_at,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(oid,oneOf(b.category,['work','scholarship','volunteer'],'category'),requireText(b,'title_en',240),requireText(b,'title_ar',240),requireText(b,'organization',240),optionalText(b,'description_en',12000),optionalText(b,'description_ar',12000),optionalText(b,'eligibility_en',4000),optionalText(b,'eligibility_ar',4000),JSON.stringify(Array.isArray(b.skills)?b.skills:[]),b.location||'',b.mode||'',b.level||'',b.deadline||null,safeUrl(b.application_url,'application_url'),b.published?1:0,b.published?now():null,ctx.user.id,now(),now()).run(); await audit(env,ctx,'opportunity.create','opportunity',oid); return ok(bodyText(await first(env.DB,`SELECT * FROM opportunities WHERE id=?`,oid)),201); }
    const opportunity=route(path,'/api/opportunities/:opportunityId'); if(opportunity&&request.method==='GET'){ const user=requireAuth(ctx); const row=await first(env.DB,`SELECT o.*,EXISTS(SELECT 1 FROM saved_opportunities s WHERE s.opportunity_id=o.id AND s.user_id=?) saved FROM opportunities o WHERE o.id=? AND (o.published=1 OR ?='MANAGER')`,user.id,opportunity.opportunityId,user.role); if(!row)return fail('NOT_FOUND','Opportunity not found',404,requestId); return ok(bodyText(row)); }
    const saveOpp=route(path,'/api/opportunities/:opportunityId/save'); if(saveOpp&&request.method==='POST'){ const user=requireAuth(ctx); const exists=await first(env.DB,`SELECT 1 ok FROM saved_opportunities WHERE user_id=? AND opportunity_id=?`,user.id,saveOpp.opportunityId); const b=await request.json().catch(()=>({})); const wanted=typeof b.saved==='boolean'?b.saved:!exists; if(wanted&&!exists)await env.DB.prepare(`INSERT INTO saved_opportunities(user_id,opportunity_id,created_at) VALUES(?,?,?)`).bind(user.id,saveOpp.opportunityId,now()).run(); if(!wanted&&exists)await env.DB.prepare(`DELETE FROM saved_opportunities WHERE user_id=? AND opportunity_id=?`).bind(user.id,saveOpp.opportunityId).run(); return ok({saved:wanted}); }

    if(path==='/api/notifications'&&request.method==='GET'){ const user=requireAuth(ctx); const unread=url.searchParams.get('status')==='unread'; return collection(await all(env.DB,`SELECT * FROM notifications WHERE user_id=? ${unread?'AND read=0':''} ORDER BY created_at DESC LIMIT 100`,user.id)); }
    if(path==='/api/notifications/read-all'&&request.method==='POST'){ const user=requireAuth(ctx); await env.DB.prepare(`UPDATE notifications SET read=1,read_at=? WHERE user_id=? AND read=0`).bind(now(),user.id).run(); return new Response(null,{status:204}); }
    const note=route(path,'/api/notifications/:notificationId/read'); if(note&&request.method==='POST'){ const user=requireAuth(ctx); await env.DB.prepare(`UPDATE notifications SET read=1,read_at=? WHERE id=? AND user_id=?`).bind(now(),note.notificationId,user.id).run(); return new Response(null,{status:204}); }
    const noteDelete=route(path,'/api/notifications/:notificationId'); if(noteDelete&&request.method==='DELETE'){ const user=requireAuth(ctx); await env.DB.prepare(`DELETE FROM notifications WHERE id=? AND user_id=?`).bind(noteDelete.notificationId,user.id).run(); return new Response(null,{status:204}); }

    if(path==='/api/manager/students'&&request.method==='GET'){ requireManager(ctx); const q=(url.searchParams.get('q')||'').trim(); return collection(await all(env.DB,`SELECT a.id,a.full_name,a.username,a.email,a.status,a.last_login_at,aa.educational_stage,aa.institution_name FROM accounts a LEFT JOIN account_academics aa ON aa.user_id=a.id WHERE a.role='STUDENT' AND (?='' OR lower(a.full_name) LIKE lower(?) OR lower(a.username) LIKE lower(?) OR lower(a.email) LIKE lower(?)) ORDER BY a.full_name LIMIT 100`,q,`%${q}%`,`%${q}%`,`%${q}%`)); }
    const managerStudent=route(path,'/api/manager/students/:userId'); if(managerStudent&&request.method==='GET'){ requireManager(ctx); const row=await first(env.DB,`SELECT a.id,a.full_name,a.username,a.email,a.status,a.last_login_at,a.joined_at,aa.* FROM accounts a LEFT JOIN account_academics aa ON aa.user_id=a.id WHERE a.id=? AND a.role='STUDENT'`,managerStudent.userId); if(!row)return fail('NOT_FOUND','Student not found',404,requestId); row.enrollments=await all(env.DB,`SELECT ce.*,c.name_en,c.name_ar FROM course_enrollments ce JOIN courses c ON c.id=ce.course_id WHERE ce.user_id=? ORDER BY ce.position`,row.id); return ok(row); }
    const status=route(path,'/api/manager/students/:userId/status'); if(status&&request.method==='PATCH'){ const manager=requireManager(ctx); if(manager.id===status.userId)return fail('SELF_STATUS_CHANGE_FORBIDDEN','Cannot change your own status',409,requestId); const b=await parseJson(request); const value=oneOf(b.status,['ACTIVE','SUSPENDED'],'status'); await env.DB.batch([env.DB.prepare(`UPDATE accounts SET status=?,updated_at=? WHERE id=?`).bind(value,now(),status.userId),...(value==='SUSPENDED'?[env.DB.prepare(`DELETE FROM account_sessions WHERE user_id=?`).bind(status.userId)]:[])]); await audit(env,ctx,`account.${value.toLowerCase()}`,'account',status.userId,status.userId); return ok({userId:status.userId,status:value}); }
    if(path==='/api/manager/reports'&&request.method==='GET'){ requireManager(ctx); const status=url.searchParams.get('status')||'Open'; return collection(await all(env.DB,`SELECT r.*,p.title post_title,a.full_name author_name FROM community_reports r JOIN community_posts p ON p.id=r.post_id JOIN accounts a ON a.id=p.user_id WHERE r.status=? ORDER BY r.created_at DESC LIMIT 100`,status)); }
    const reportAdmin=route(path,'/api/manager/reports/:reportId'); if(reportAdmin&&request.method==='PATCH'){ requireManager(ctx); const b=await parseJson(request); const value=oneOf(b.status,['Resolved','Dismissed'],'status'); const reportRow=await first(env.DB,`SELECT r.*,p.user_id author_id FROM community_reports r JOIN community_posts p ON p.id=r.post_id WHERE r.id=?`,reportAdmin.reportId); if(!reportRow)return fail('NOT_FOUND','Report not found',404,requestId); const stmts=[env.DB.prepare(`UPDATE community_reports SET status=?,resolved_by=?,resolved_at=?,resolution_note=? WHERE id=? AND status='Open'`).bind(value,ctx.user.id,now(),b.resolution_note||'',reportRow.id)]; if(b.moderation_action==='lock')stmts.push(env.DB.prepare(`UPDATE community_posts SET locked=1,updated_at=? WHERE id=?`).bind(now(),reportRow.post_id)); if(b.moderation_action==='delete')stmts.push(env.DB.prepare(`DELETE FROM community_posts WHERE id=?`).bind(reportRow.post_id)); await env.DB.batch(stmts); await audit(env,ctx,'report.resolve','report',reportRow.id,reportRow.author_id,{status:value,action:b.moderation_action||'none'}); return ok({id:reportRow.id,status:value}); }
    if(path==='/api/manager/audit'&&request.method==='GET'){ requireManager(ctx); return collection(await all(env.DB,`SELECT * FROM audit_events ORDER BY created_at DESC LIMIT 200`)); }

    return fail('NOT_FOUND','API route not found',404,requestId);
  }catch(error){
    console.error(JSON.stringify({requestId,path,method:request.method,status:error.status||500,code:error.code||'INTERNAL_ERROR',message:error.message}));
    if(error instanceof ValidationError)return fail('VALIDATION_ERROR',error.message,422,requestId,error.fields);
    return fail(error.code||'INTERNAL_ERROR',error.status?error.message:'Unexpected server error',error.status||500,requestId);
  }
}

export async function scheduledJobs(env){
  const current=now(); const future=new Date(Date.now()+30*60000).toISOString();
  const reminders=await all(env.DB,`SELECT s.*,a.full_name FROM schedule_items s JOIN accounts a ON a.id=s.user_id JOIN account_settings st ON st.user_id=s.user_id WHERE s.reminder=1 AND s.completed=0 AND st.study_reminders=1 AND s.starts_at BETWEEN ? AND ? LIMIT 100`,current,future);
  for(const item of reminders) await createNotification(env,{userId:item.user_id,category:'study',event:'schedule.reminder',title:'Study session coming up',body:item.title,path:'/schedule',sourceType:'schedule',sourceId:item.id,dedupeKey:`schedule:${item.id}:30m`});
  await env.DB.prepare(`DELETE FROM account_sessions WHERE expires_at<=?`).bind(current).run();
}
